//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace OpenTracker.Core
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OpenTrackerDbContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OpenTrackerDbContext object using the connection string found in the 'OpenTrackerDbContext' section of the application configuration file.
        /// </summary>
        public OpenTrackerDbContext() : base("name=OpenTrackerDbContext", "OpenTrackerDbContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OpenTrackerDbContext object.
        /// </summary>
        public OpenTrackerDbContext(string connectionString) : base(connectionString, "OpenTrackerDbContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OpenTrackerDbContext object.
        /// </summary>
        public OpenTrackerDbContext(EntityConnection connection) : base(connection, "OpenTrackerDbContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<categories> categories
        {
            get
            {
                if ((_categories == null))
                {
                    _categories = base.CreateObjectSet<categories>("categories");
                }
                return _categories;
            }
        }
        private ObjectSet<categories> _categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<torrents_files> torrents_files
        {
            get
            {
                if ((_torrents_files == null))
                {
                    _torrents_files = base.CreateObjectSet<torrents_files>("torrents_files");
                }
                return _torrents_files;
            }
        }
        private ObjectSet<torrents_files> _torrents_files;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<peers> peers
        {
            get
            {
                if ((_peers == null))
                {
                    _peers = base.CreateObjectSet<peers>("peers");
                }
                return _peers;
            }
        }
        private ObjectSet<peers> _peers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<comments> comments
        {
            get
            {
                if ((_comments == null))
                {
                    _comments = base.CreateObjectSet<comments>("comments");
                }
                return _comments;
            }
        }
        private ObjectSet<comments> _comments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<users> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<users>("users");
                }
                return _users;
            }
        }
        private ObjectSet<users> _users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<torrents> torrents
        {
            get
            {
                if ((_torrents == null))
                {
                    _torrents = base.CreateObjectSet<torrents>("torrents");
                }
                return _torrents;
            }
        }
        private ObjectSet<torrents> _torrents;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocategories(categories categories)
        {
            base.AddObject("categories", categories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the torrents_files EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotorrents_files(torrents_files torrents_files)
        {
            base.AddObject("torrents_files", torrents_files);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the peers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopeers(peers peers)
        {
            base.AddObject("peers", peers);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the comments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocomments(comments comments)
        {
            base.AddObject("comments", comments);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(users users)
        {
            base.AddObject("users", users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the torrents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotorrents(torrents torrents)
        {
            base.AddObject("torrents", torrents);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbContext", Name="categories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class categories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new categories object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="image">Initial value of the image property.</param>
        /// <param name="cat_desc">Initial value of the cat_desc property.</param>
        public static categories Createcategories(global::System.Int64 id, global::System.String name, global::System.String image, global::System.String cat_desc)
        {
            categories categories = new categories();
            categories.id = id;
            categories.name = name;
            categories.image = image;
            categories.cat_desc = cat_desc;
            return categories;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String image
        {
            get
            {
                return _image;
            }
            set
            {
                OnimageChanging(value);
                ReportPropertyChanging("image");
                _image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("image");
                OnimageChanged();
            }
        }
        private global::System.String _image;
        partial void OnimageChanging(global::System.String value);
        partial void OnimageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cat_desc
        {
            get
            {
                return _cat_desc;
            }
            set
            {
                Oncat_descChanging(value);
                ReportPropertyChanging("cat_desc");
                _cat_desc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cat_desc");
                Oncat_descChanged();
            }
        }
        private global::System.String _cat_desc;
        partial void Oncat_descChanging(global::System.String value);
        partial void Oncat_descChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbContext", Name="comments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new comments object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="userid">Initial value of the userid property.</param>
        /// <param name="torrentid">Initial value of the torrentid property.</param>
        /// <param name="added">Initial value of the added property.</param>
        /// <param name="comment">Initial value of the comment property.</param>
        /// <param name="original_text">Initial value of the original_text property.</param>
        /// <param name="editedby">Initial value of the editedby property.</param>
        /// <param name="editedate">Initial value of the editedate property.</param>
        public static comments Createcomments(global::System.Int64 id, global::System.Int64 userid, global::System.Int64 torrentid, global::System.Int32 added, global::System.String comment, global::System.String original_text, global::System.Int64 editedby, global::System.Int32 editedate)
        {
            comments comments = new comments();
            comments.id = id;
            comments.userid = userid;
            comments.torrentid = torrentid;
            comments.added = added;
            comments.comment = comment;
            comments.original_text = original_text;
            comments.editedby = editedby;
            comments.editedate = editedate;
            return comments;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userid
        {
            get
            {
                return _userid;
            }
            set
            {
                OnuseridChanging(value);
                ReportPropertyChanging("userid");
                _userid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userid");
                OnuseridChanged();
            }
        }
        private global::System.Int64 _userid;
        partial void OnuseridChanging(global::System.Int64 value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 torrentid
        {
            get
            {
                return _torrentid;
            }
            set
            {
                OntorrentidChanging(value);
                ReportPropertyChanging("torrentid");
                _torrentid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("torrentid");
                OntorrentidChanged();
            }
        }
        private global::System.Int64 _torrentid;
        partial void OntorrentidChanging(global::System.Int64 value);
        partial void OntorrentidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 added
        {
            get
            {
                return _added;
            }
            set
            {
                OnaddedChanging(value);
                ReportPropertyChanging("added");
                _added = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("added");
                OnaddedChanged();
            }
        }
        private global::System.Int32 _added;
        partial void OnaddedChanging(global::System.Int32 value);
        partial void OnaddedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String comment
        {
            get
            {
                return _comment;
            }
            set
            {
                OncommentChanging(value);
                ReportPropertyChanging("comment");
                _comment = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("comment");
                OncommentChanged();
            }
        }
        private global::System.String _comment;
        partial void OncommentChanging(global::System.String value);
        partial void OncommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String original_text
        {
            get
            {
                return _original_text;
            }
            set
            {
                Onoriginal_textChanging(value);
                ReportPropertyChanging("original_text");
                _original_text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("original_text");
                Onoriginal_textChanged();
            }
        }
        private global::System.String _original_text;
        partial void Onoriginal_textChanging(global::System.String value);
        partial void Onoriginal_textChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 editedby
        {
            get
            {
                return _editedby;
            }
            set
            {
                OneditedbyChanging(value);
                ReportPropertyChanging("editedby");
                _editedby = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("editedby");
                OneditedbyChanged();
            }
        }
        private global::System.Int64 _editedby;
        partial void OneditedbyChanging(global::System.Int64 value);
        partial void OneditedbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 editedate
        {
            get
            {
                return _editedate;
            }
            set
            {
                OneditedateChanging(value);
                ReportPropertyChanging("editedate");
                _editedate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("editedate");
                OneditedateChanged();
            }
        }
        private global::System.Int32 _editedate;
        partial void OneditedateChanging(global::System.Int32 value);
        partial void OneditedateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbContext", Name="peers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class peers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new peers object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="torrentid">Initial value of the torrentid property.</param>
        /// <param name="peer_id">Initial value of the peer_id property.</param>
        /// <param name="ip">Initial value of the ip property.</param>
        /// <param name="port">Initial value of the port property.</param>
        /// <param name="uploaded">Initial value of the uploaded property.</param>
        /// <param name="downloaded">Initial value of the downloaded property.</param>
        /// <param name="left">Initial value of the left property.</param>
        /// <param name="seeding">Initial value of the seeding property.</param>
        /// <param name="userid">Initial value of the userid property.</param>
        /// <param name="connectable">Initial value of the connectable property.</param>
        /// <param name="useragent">Initial value of the useragent property.</param>
        public static peers Createpeers(global::System.Int64 id, global::System.Int64 torrentid, global::System.String peer_id, global::System.String ip, global::System.Int32 port, global::System.Decimal uploaded, global::System.Decimal downloaded, global::System.Decimal left, global::System.Int64 seeding, global::System.Int64 userid, global::System.Int64 connectable, global::System.String useragent)
        {
            peers peers = new peers();
            peers.id = id;
            peers.torrentid = torrentid;
            peers.peer_id = peer_id;
            peers.ip = ip;
            peers.port = port;
            peers.uploaded = uploaded;
            peers.downloaded = downloaded;
            peers.left = left;
            peers.seeding = seeding;
            peers.userid = userid;
            peers.connectable = connectable;
            peers.useragent = useragent;
            return peers;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 torrentid
        {
            get
            {
                return _torrentid;
            }
            set
            {
                OntorrentidChanging(value);
                ReportPropertyChanging("torrentid");
                _torrentid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("torrentid");
                OntorrentidChanged();
            }
        }
        private global::System.Int64 _torrentid;
        partial void OntorrentidChanging(global::System.Int64 value);
        partial void OntorrentidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String peer_id
        {
            get
            {
                return _peer_id;
            }
            set
            {
                Onpeer_idChanging(value);
                ReportPropertyChanging("peer_id");
                _peer_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("peer_id");
                Onpeer_idChanged();
            }
        }
        private global::System.String _peer_id;
        partial void Onpeer_idChanging(global::System.String value);
        partial void Onpeer_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ip
        {
            get
            {
                return _ip;
            }
            set
            {
                OnipChanging(value);
                ReportPropertyChanging("ip");
                _ip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ip");
                OnipChanged();
            }
        }
        private global::System.String _ip;
        partial void OnipChanging(global::System.String value);
        partial void OnipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 port
        {
            get
            {
                return _port;
            }
            set
            {
                OnportChanging(value);
                ReportPropertyChanging("port");
                _port = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("port");
                OnportChanged();
            }
        }
        private global::System.Int32 _port;
        partial void OnportChanging(global::System.Int32 value);
        partial void OnportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal uploaded
        {
            get
            {
                return _uploaded;
            }
            set
            {
                OnuploadedChanging(value);
                ReportPropertyChanging("uploaded");
                _uploaded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uploaded");
                OnuploadedChanged();
            }
        }
        private global::System.Decimal _uploaded;
        partial void OnuploadedChanging(global::System.Decimal value);
        partial void OnuploadedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal downloaded
        {
            get
            {
                return _downloaded;
            }
            set
            {
                OndownloadedChanging(value);
                ReportPropertyChanging("downloaded");
                _downloaded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("downloaded");
                OndownloadedChanged();
            }
        }
        private global::System.Decimal _downloaded;
        partial void OndownloadedChanging(global::System.Decimal value);
        partial void OndownloadedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal left
        {
            get
            {
                return _left;
            }
            set
            {
                OnleftChanging(value);
                ReportPropertyChanging("left");
                _left = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("left");
                OnleftChanged();
            }
        }
        private global::System.Decimal _left;
        partial void OnleftChanging(global::System.Decimal value);
        partial void OnleftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 seeding
        {
            get
            {
                return _seeding;
            }
            set
            {
                OnseedingChanging(value);
                ReportPropertyChanging("seeding");
                _seeding = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("seeding");
                OnseedingChanged();
            }
        }
        private global::System.Int64 _seeding;
        partial void OnseedingChanging(global::System.Int64 value);
        partial void OnseedingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userid
        {
            get
            {
                return _userid;
            }
            set
            {
                OnuseridChanging(value);
                ReportPropertyChanging("userid");
                _userid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userid");
                OnuseridChanged();
            }
        }
        private global::System.Int64 _userid;
        partial void OnuseridChanging(global::System.Int64 value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String passkey
        {
            get
            {
                return _passkey;
            }
            set
            {
                OnpasskeyChanging(value);
                ReportPropertyChanging("passkey");
                _passkey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("passkey");
                OnpasskeyChanged();
            }
        }
        private global::System.String _passkey;
        partial void OnpasskeyChanging(global::System.String value);
        partial void OnpasskeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 connectable
        {
            get
            {
                return _connectable;
            }
            set
            {
                OnconnectableChanging(value);
                ReportPropertyChanging("connectable");
                _connectable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("connectable");
                OnconnectableChanged();
            }
        }
        private global::System.Int64 _connectable;
        partial void OnconnectableChanging(global::System.Int64 value);
        partial void OnconnectableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String useragent
        {
            get
            {
                return _useragent;
            }
            set
            {
                OnuseragentChanging(value);
                ReportPropertyChanging("useragent");
                _useragent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("useragent");
                OnuseragentChanged();
            }
        }
        private global::System.String _useragent;
        partial void OnuseragentChanging(global::System.String value);
        partial void OnuseragentChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbContext", Name="torrents")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class torrents : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new torrents object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="categoryid">Initial value of the categoryid property.</param>
        /// <param name="info_hash">Initial value of the info_hash property.</param>
        /// <param name="torrentname">Initial value of the torrentname property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="description_small">Initial value of the description_small property.</param>
        /// <param name="added">Initial value of the added property.</param>
        /// <param name="size">Initial value of the size property.</param>
        /// <param name="numfiles">Initial value of the numfiles property.</param>
        /// <param name="views">Initial value of the views property.</param>
        /// <param name="snatches">Initial value of the snatches property.</param>
        public static torrents Createtorrents(global::System.Int64 id, global::System.Int64 categoryid, global::System.String info_hash, global::System.String torrentname, global::System.String description, global::System.String description_small, global::System.Int32 added, global::System.Decimal size, global::System.Int64 numfiles, global::System.Int64 views, global::System.Int64 snatches)
        {
            torrents torrents = new torrents();
            torrents.id = id;
            torrents.categoryid = categoryid;
            torrents.info_hash = info_hash;
            torrents.torrentname = torrentname;
            torrents.description = description;
            torrents.description_small = description_small;
            torrents.added = added;
            torrents.size = size;
            torrents.numfiles = numfiles;
            torrents.views = views;
            torrents.snatches = snatches;
            return torrents;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 categoryid
        {
            get
            {
                return _categoryid;
            }
            set
            {
                OncategoryidChanging(value);
                ReportPropertyChanging("categoryid");
                _categoryid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("categoryid");
                OncategoryidChanged();
            }
        }
        private global::System.Int64 _categoryid;
        partial void OncategoryidChanging(global::System.Int64 value);
        partial void OncategoryidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String info_hash
        {
            get
            {
                return _info_hash;
            }
            set
            {
                Oninfo_hashChanging(value);
                ReportPropertyChanging("info_hash");
                _info_hash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("info_hash");
                Oninfo_hashChanged();
            }
        }
        private global::System.String _info_hash;
        partial void Oninfo_hashChanging(global::System.String value);
        partial void Oninfo_hashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String torrentname
        {
            get
            {
                return _torrentname;
            }
            set
            {
                OntorrentnameChanging(value);
                ReportPropertyChanging("torrentname");
                _torrentname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("torrentname");
                OntorrentnameChanged();
            }
        }
        private global::System.String _torrentname;
        partial void OntorrentnameChanging(global::System.String value);
        partial void OntorrentnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description_small
        {
            get
            {
                return _description_small;
            }
            set
            {
                Ondescription_smallChanging(value);
                ReportPropertyChanging("description_small");
                _description_small = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description_small");
                Ondescription_smallChanged();
            }
        }
        private global::System.String _description_small;
        partial void Ondescription_smallChanging(global::System.String value);
        partial void Ondescription_smallChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 added
        {
            get
            {
                return _added;
            }
            set
            {
                OnaddedChanging(value);
                ReportPropertyChanging("added");
                _added = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("added");
                OnaddedChanged();
            }
        }
        private global::System.Int32 _added;
        partial void OnaddedChanging(global::System.Int32 value);
        partial void OnaddedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal size
        {
            get
            {
                return _size;
            }
            set
            {
                OnsizeChanging(value);
                ReportPropertyChanging("size");
                _size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("size");
                OnsizeChanged();
            }
        }
        private global::System.Decimal _size;
        partial void OnsizeChanging(global::System.Decimal value);
        partial void OnsizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 numfiles
        {
            get
            {
                return _numfiles;
            }
            set
            {
                OnnumfilesChanging(value);
                ReportPropertyChanging("numfiles");
                _numfiles = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numfiles");
                OnnumfilesChanged();
            }
        }
        private global::System.Int64 _numfiles;
        partial void OnnumfilesChanging(global::System.Int64 value);
        partial void OnnumfilesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 views
        {
            get
            {
                return _views;
            }
            set
            {
                OnviewsChanging(value);
                ReportPropertyChanging("views");
                _views = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("views");
                OnviewsChanged();
            }
        }
        private global::System.Int64 _views;
        partial void OnviewsChanging(global::System.Int64 value);
        partial void OnviewsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 snatches
        {
            get
            {
                return _snatches;
            }
            set
            {
                OnsnatchesChanging(value);
                ReportPropertyChanging("snatches");
                _snatches = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("snatches");
                OnsnatchesChanged();
            }
        }
        private global::System.Int64 _snatches;
        partial void OnsnatchesChanging(global::System.Int64 value);
        partial void OnsnatchesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> last_action
        {
            get
            {
                return _last_action;
            }
            set
            {
                Onlast_actionChanging(value);
                ReportPropertyChanging("last_action");
                _last_action = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("last_action");
                Onlast_actionChanged();
            }
        }
        private Nullable<global::System.Int32> _last_action;
        partial void Onlast_actionChanging(Nullable<global::System.Int32> value);
        partial void Onlast_actionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String visible
        {
            get
            {
                return _visible;
            }
            set
            {
                OnvisibleChanging(value);
                ReportPropertyChanging("visible");
                _visible = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("visible");
                OnvisibleChanged();
            }
        }
        private global::System.String _visible;
        partial void OnvisibleChanging(global::System.String value);
        partial void OnvisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String banned
        {
            get
            {
                return _banned;
            }
            set
            {
                OnbannedChanging(value);
                ReportPropertyChanging("banned");
                _banned = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("banned");
                OnbannedChanged();
            }
        }
        private global::System.String _banned;
        partial void OnbannedChanging(global::System.String value);
        partial void OnbannedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> owner
        {
            get
            {
                return _owner;
            }
            set
            {
                OnownerChanging(value);
                ReportPropertyChanging("owner");
                _owner = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("owner");
                OnownerChanged();
            }
        }
        private Nullable<global::System.Int64> _owner;
        partial void OnownerChanging(Nullable<global::System.Int64> value);
        partial void OnownerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String client_created_by
        {
            get
            {
                return _client_created_by;
            }
            set
            {
                Onclient_created_byChanging(value);
                ReportPropertyChanging("client_created_by");
                _client_created_by = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("client_created_by");
                Onclient_created_byChanged();
            }
        }
        private global::System.String _client_created_by;
        partial void Onclient_created_byChanging(global::System.String value);
        partial void Onclient_created_byChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbContext", Name="torrents_files")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class torrents_files : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new torrents_files object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="torrentid">Initial value of the torrentid property.</param>
        /// <param name="filename">Initial value of the filename property.</param>
        /// <param name="filesize">Initial value of the filesize property.</param>
        public static torrents_files Createtorrents_files(global::System.Int64 id, global::System.Int64 torrentid, global::System.String filename, global::System.Decimal filesize)
        {
            torrents_files torrents_files = new torrents_files();
            torrents_files.id = id;
            torrents_files.torrentid = torrentid;
            torrents_files.filename = filename;
            torrents_files.filesize = filesize;
            return torrents_files;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 torrentid
        {
            get
            {
                return _torrentid;
            }
            set
            {
                OntorrentidChanging(value);
                ReportPropertyChanging("torrentid");
                _torrentid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("torrentid");
                OntorrentidChanged();
            }
        }
        private global::System.Int64 _torrentid;
        partial void OntorrentidChanging(global::System.Int64 value);
        partial void OntorrentidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String filename
        {
            get
            {
                return _filename;
            }
            set
            {
                OnfilenameChanging(value);
                ReportPropertyChanging("filename");
                _filename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("filename");
                OnfilenameChanged();
            }
        }
        private global::System.String _filename;
        partial void OnfilenameChanging(global::System.String value);
        partial void OnfilenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal filesize
        {
            get
            {
                return _filesize;
            }
            set
            {
                OnfilesizeChanging(value);
                ReportPropertyChanging("filesize");
                _filesize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("filesize");
                OnfilesizeChanged();
            }
        }
        private global::System.Decimal _filesize;
        partial void OnfilesizeChanging(global::System.Decimal value);
        partial void OnfilesizeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbContext", Name="users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new users object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="passkey">Initial value of the passkey property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="passhash">Initial value of the passhash property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="activated">Initial value of the activated property.</param>
        /// <param name="class">Initial value of the class property.</param>
        /// <param name="banned">Initial value of the banned property.</param>
        /// <param name="uploaded">Initial value of the uploaded property.</param>
        /// <param name="downloaded">Initial value of the downloaded property.</param>
        public static users Createusers(global::System.Int64 id, global::System.String passkey, global::System.String username, global::System.String passhash, global::System.String email, global::System.Int64 activated, global::System.Int64 @class, global::System.Int64 banned, global::System.Decimal uploaded, global::System.Decimal downloaded)
        {
            users users = new users();
            users.id = id;
            users.passkey = passkey;
            users.username = username;
            users.passhash = passhash;
            users.email = email;
            users.activated = activated;
            users.@class = @class;
            users.banned = banned;
            users.uploaded = uploaded;
            users.downloaded = downloaded;
            return users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String passkey
        {
            get
            {
                return _passkey;
            }
            set
            {
                OnpasskeyChanging(value);
                ReportPropertyChanging("passkey");
                _passkey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("passkey");
                OnpasskeyChanged();
            }
        }
        private global::System.String _passkey;
        partial void OnpasskeyChanging(global::System.String value);
        partial void OnpasskeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String passhash
        {
            get
            {
                return _passhash;
            }
            set
            {
                OnpasshashChanging(value);
                ReportPropertyChanging("passhash");
                _passhash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("passhash");
                OnpasshashChanged();
            }
        }
        private global::System.String _passhash;
        partial void OnpasshashChanging(global::System.String value);
        partial void OnpasshashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 activated
        {
            get
            {
                return _activated;
            }
            set
            {
                OnactivatedChanging(value);
                ReportPropertyChanging("activated");
                _activated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("activated");
                OnactivatedChanged();
            }
        }
        private global::System.Int64 _activated;
        partial void OnactivatedChanging(global::System.Int64 value);
        partial void OnactivatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 @class
        {
            get
            {
                return _class;
            }
            set
            {
                OnclassChanging(value);
                ReportPropertyChanging("class");
                _class = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("class");
                OnclassChanged();
            }
        }
        private global::System.Int64 _class;
        partial void OnclassChanging(global::System.Int64 value);
        partial void OnclassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 banned
        {
            get
            {
                return _banned;
            }
            set
            {
                OnbannedChanging(value);
                ReportPropertyChanging("banned");
                _banned = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("banned");
                OnbannedChanged();
            }
        }
        private global::System.Int64 _banned;
        partial void OnbannedChanging(global::System.Int64 value);
        partial void OnbannedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal uploaded
        {
            get
            {
                return _uploaded;
            }
            set
            {
                OnuploadedChanging(value);
                ReportPropertyChanging("uploaded");
                _uploaded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uploaded");
                OnuploadedChanged();
            }
        }
        private global::System.Decimal _uploaded;
        partial void OnuploadedChanging(global::System.Decimal value);
        partial void OnuploadedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal downloaded
        {
            get
            {
                return _downloaded;
            }
            set
            {
                OndownloadedChanging(value);
                ReportPropertyChanging("downloaded");
                _downloaded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("downloaded");
                OndownloadedChanged();
            }
        }
        private global::System.Decimal _downloaded;
        partial void OndownloadedChanging(global::System.Decimal value);
        partial void OndownloadedChanged();

        #endregion
    
    }

    #endregion
    
}
